### ISSUE TITLE
Probably don't want to call the canvas element `xss-demo`. 

### ISSUE THREAD

**Issue by daniellockard** [myliang/x-spreadsheet#1]
XSS refers to Cross Site Scripting.

**Comment by myliang** [comment]
<div id="xss-demo"></div> 
not <canvas id="xss-demo"></div>

**Comment by Yamboy1** [comment]
how about calling it `spreadsheet-demo`?
@daniellockard
@myliang

**Comment by Yamboy1** [comment]
Also, I'm seeing references to xss-* through the source code, these should be changed as well

**Comment by myliang** [comment]
like this xdss
