### ISSUE TITLE
Scroll event bubbles out of canvas (at least in demo)

### ISSUE THREAD

**Issue by mrkev** [myliang/x-spreadsheet#10]
Hello!

First of all, loving the project-- this looks awesome.

Next, the issue I noticed. Not sure if this is by design or not, but I thought I'd share that I found it a little weird. The scroll event seems to leave the canvas and so as the spreadsheet scrolls the whole thing moves up and down. 

I imagine this could be fixed by disabling scroll in the container element(s). CSS is probably enough. Pointing it out not only because it's present in the example, but also because it's worth thinking if this should be the default behaviour or not.

Below is a screen recording of what I mean-- notice how as the cells scrolls the whole interface bounces around (as things do by default on macOS).

![scroll image](https://user-images.githubusercontent.com/1285131/51863768-e7167100-230f-11e9-9a8d-673893a38814.gif)

FYI, I'm using Chrome 71.0.3578.98 on macOS 10.14.2 (18C54).

**Comment by Zecio** [comment]
安装的最新版本，在canvas区域滚动，滚动事件冒泡了，整个页面也跟着滚动

**Comment by myliang** [comment]
> 安装的最新版本，在canvas区域滚动，滚动事件冒泡了，整个页面也跟着滚动
> 浏览器版本： Chrome75.0.3770.142
> 系统：macOS 10.14.5

暂时macos没有测试过。。。

**Comment by Zecio** [comment]
windows测试了下也是有同样的问题的，canvas我是放在一个div里面，不是撑满全屏的情况下

**Comment by myliang** [comment]
view: {
    height: () => document.documentElement.clientHeight,
    width: () => document.documentElement.clientWidth,
  },
需要设置这两个值

**Comment by Zecio** [comment]
有的呢，我再研究下看看吧，谢谢
