### ISSUE TITLE
您好，怎么设置表格的默认行数

### ISSUE THREAD

**Issue by yanlingsishao** [myliang/x-spreadsheet#100]
您好，怎么设置表格的默认行数

**Comment by myliang** [comment]
看看readme : default option
```javascript
new Spreadsheet("#x-spreadsheet-demo", {
  row: {len: 20},
  col: {len: 30},
})
```

**Comment by yanlingsishao** [comment]
这是默认的，如果我想动态改变这个值呢，有没有什么方法1

**Comment by yanlingsishao** [comment]
就是在我loadData之后，根据loadData的数据动态增加行

**Comment by myliang** [comment]
可以的 
data.rows.len
data.cols.len

**Comment by myliang** [comment]
data 为loadData方法的参数

**Comment by yanlingsishao** [comment]
[](url)
![image](https://user-images.githubusercontent.com/28887713/56023539-a5a73680-5d40-11e9-8c2f-0ae241f3f8e0.png)
试了这个rows里面len，不管用

**Comment by myliang** [comment]
等我过两天看看，先走电脑不在身边


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by yanlingsishao** [comment]
好的，麻烦了，我这边的解决方式是，先去掉子元素，重新加载option。

**Comment by zhouhuan0910** [comment]
> 好的，麻烦了，我这边的解决方式是，先去掉子元素，重新加载option。
重新加载option可以吗，我再第一次加载整个表格的时候设置col.len为任意值都不生效

**Comment by doukai** [comment]
请问data参数既然是个Array数字，怎么会有data.rows.len和data.cols.len这两个属性呢？
