### ISSUE TITLE
怎么样设置整列只能输入数字

### ISSUE THREAD

**Issue by yizhichenfamily** [myliang/x-spreadsheet#104]
1.我想数字表格中整列只能输入数字，请问一下怎么样进行设置；2.我想将某一列的宽度单独设置，请问参数是一个

**Comment by myliang** [comment]
1 右键菜单--数据验证
2 可以动态调整，鼠标放到行头，列头拖动调整即可

**Comment by yizhichenfamily** [comment]
1.关于你的右键菜单能否详细一点；
2.我知道可以动态调整，但是我想表格在渲染的时候，就可以将某列宽度直接加上去

**Comment by myliang** [comment]
你设计好了，之后其他人输入不就可以了吗？

**Comment by yizhichenfamily** [comment]
现在就是需要表格在初始化的时候，进行设置

**Comment by myliang** [comment]
不支持整列限制

**Comment by myliang** [comment]
但是支持区间

**Comment by yizhichenfamily** [comment]
整列的宽度能否设置呢

**Comment by myliang** [comment]
loadData时候设置，其实我感觉你应该这样：设计表头模板，之后填写数据
尔不是应该这样再代码中写死

**Comment by yizhichenfamily** [comment]
目前我是在loadData中已经设置好了表头，但是不知道怎么样设置你所说的区间设置，

**Comment by myliang** [comment]
> 目前我是在loadData中已经设置好了表头，但是不知道怎么样设置你所说的区间设置，

建议不要这样操作，
代码设置需要知道的细节太多了，还是页面操作比较好，之后把设计好的保存起来，要填写数据的时候再读出来就可以了。
![image](https://user-images.githubusercontent.com/718858/56111867-ea72dd80-5f8b-11e9-86fc-434f669e7ea5.png)

**Comment by yizhichenfamily** [comment]
当我把数据输入错误的时候，发现好像没有那个参数表示当前数据是错误的

**Comment by myliang** [comment]
1 暂时获取不到错误信息，但是页面是可以看到的，可以添加个方法，数据是否校验通过
2 后面会加这个功能

**Comment by yizhichenfamily** [comment]
1.关于你所说的数据是否校验通过的方法是，暂时在1.0.14版本是没有的对吗

**Comment by myliang** [comment]
用1.0.16版本，
1 我新加个了方法validate() 可以验证是否有错误
2 选项添加了showContextmenu控制右键菜单是否显示

**Comment by yizhichenfamily** [comment]
好的，谢谢
