### ISSUE TITLE
有没有办法 把x-spreedsheet表格里面的数据复制到系统剪贴板上？或者从系统剪贴板复制到表格里面？

### ISSUE THREAD

**Issue by qflash** [myliang/x-spreadsheet#105]

**Comment by myliang** [comment]
你是说excel的数据复制到剪切板只有再粘贴到x-spreadsheet中，是这个意思吗啊？如果是这样暂时做不到

**Comment by qflash** [comment]
如果是纯文本，只是粘贴一段文字到某一个单元格里面，这种呢？如果全部是手工录入，太恼火了。

**Comment by myliang** [comment]
其实是需要一个导入的功能的，需要你自己的后台代码支持，就解决你说的问题了

**Comment by qflash** [comment]
不是导入，是个别的某个字段，需要复制进去，和复制出来。

**Comment by myliang** [comment]
其实是可以支持的，只能是一个单元一个单元格的内容复制，双击出现输入框，复制到里面就好了

**Comment by qflash** [comment]
明白了。多谢。
另外期待表格的复制粘贴功能。

**Comment by johnhemming** [comment]
To do this properly you need to interface with the clipboard API.    Spreadsheets tend to be structured like CSV files, but with tabs rather than commas.

**Comment by xioxin** [comment]
https://www.w3.org/TR/clipboard-apis/#async-clipboard-api
