### ISSUE TITLE
ajax返回json数据赋值给x-spreadsheet的loadData方法不显示

### ISSUE THREAD

**Issue by LiuHaiL** [myliang/x-spreadsheet#106]
{
cells: [
{
text: "所属单位"
},
{
text: "所属片区"
},
{
text: "油站名称"
},
{
text: "站点类型"
},
{
text: "站点大小"
},
{
text: "站点位置"
},
{
text: "加油员工工号或特征描述"
},
{
text: "便利店员工工号或特征描述"
},
{
text: "执行日期"
},
{
text: "星期"
},
{
text: "进站时间"
},
{
text: "离站时间"
}
]
}
]

**Comment by LiuHaiL** [comment]
![微信截图_20190415160752](https://user-images.githubusercontent.com/41782624/56119029-d1732800-5f9d-11e9-8486-65b401354b0a.png)

**Comment by LiuHaiL** [comment]
![微信截图_20190415164540](https://user-images.githubusercontent.com/41782624/56119078-f23b7d80-5f9d-11e9-8f04-d229abeae439.png)
该怎么赋值啊！

**Comment by myliang** [comment]
rows是个map

**Comment by myliang** [comment]
https://github.com/myliang/x-spreadsheet/blob/master/index.html
看看这个

**Comment by LiuHaiL** [comment]
是根据后端返回的值 直接在loadData方法中 map遍历吗

**Comment by LiuHaiL** [comment]
不能在后端直接生成前端所需要的格式 然后直接赋值给前端不行吗

**Comment by myliang** [comment]
直接后台返回这样的数据不就行了吗？
![image](https://user-images.githubusercontent.com/718858/56123686-89f19980-5fa7-11e9-97df-25706a76d307.png)

**Comment by LiuHaiL** [comment]
我第一次问的问题就是后台返回的数据格式  直接赋值给loadData下面的rows这个里面的格式的！ 不行！ 无法显示

**Comment by myliang** [comment]
用最新版本，你数据的格式不对，贴出你后台返回的数据

**Comment by LiuHaiL** [comment]
https://user-images.githubusercontent.com/41782624/56119029-d1732800-5f9d-11e9-8486-65b401354b0a.png 返回的数据

**Comment by myliang** [comment]
loadData方法的数据应该数据这个样的
https://github.com/myliang/x-spreadsheet/blob/master/index.html
看这个页面的loadData
用最新的版本1.0.16
