### ISSUE TITLE
导出表格

### ISSUE THREAD

**Issue by yanlingsishao** [myliang/x-spreadsheet#110]
导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀

**Comment by myliang** [comment]
> 导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀

以后有时间，我会添加后台语言的导入导出支持

**Comment by hellcos** [comment]
> 导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀
求怎么处理的，我这边急需导出功能，感谢！

**Comment by myliang** [comment]
> > 导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀
> > 求怎么处理的，我这边急需导出功能，感谢！

你看看style自己转一下还是比较容易的，我暂时没有时间处理，建议生成环境暂时不要使用，如果现有功能可以满足你的需要可以用

**Comment by hellcos** [comment]
源码里面是不带坐标的，你是怎么解决这个问题的呢？用的像素绝对位置吗？


 
---原始邮件---
发件人: "yuliang.liang"<notifications@github.com>
发送时间: 2019年8月12日 22:38:13
收件人: "myliang/x-spreadsheet"<x-spreadsheet@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"hellcos"<hellocs@foxmail.com>;
主题: Re: [myliang/x-spreadsheet] 导出表格 (#110)


  
导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀
 求怎么处理的，我这边急需导出功能，感谢！
   
你看看style自己转一下还是比较容易的，我暂时没有时间处理，建议生成环境暂时不要使用，如果现有功能可以满足你的需要可以用

**Comment by myliang** [comment]
> 源码里面是不带坐标的，你是怎么解决这个问题的呢？用的像素绝对位置吗？
> […](#)
> ---原始邮件--- 发件人: "yuliang.liang"<notifications@github.com> 发送时间: 2019年8月12日 22:38:13 收件人: "myliang/x-spreadsheet"<x-spreadsheet@noreply.github.com>; 抄送: "Comment"<comment@noreply.github.com>;"hellcos"<hellocs@foxmail.com>; 主题: Re: [myliang/x-spreadsheet] 导出表格 (#110) 导出表格我现在只能做到无格式的导出，感觉带有格式的好难呀 求怎么处理的，我这边急需导出功能，感谢！ 你看看style自己转一下还是比较容易的，我暂时没有时间处理，建议生成环境暂时不要使用，如果现有功能可以满足你的需要可以用 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你先看一下保存的数据就知道怎么回事了
