### ISSUE TITLE
关于单元格校验问题

### ISSUE THREAD

**Issue by yizhichenfamily** [myliang/x-spreadsheet#111]
1.当我输入的数据出现错误的时候，有一个红色的标记出现在单元格内，但是我删掉数据后，发现单元格内必须输入正确的数据才能去除红色标记，若我不想输入的时候，红色标记会一直存在
2.能否新增一个限制的只能输入字母和数字并且不能超过13位（这只是打个比方）
3.个人建议：能否自己输入自己想要的数据的限制

**Comment by myliang** [comment]
可以添加个自定义规则

**Comment by myliang** [comment]
后面我考虑下，要不要加把，如果加自定了，设计到通用性的问题，比如自定义格式，如果导出excel,如何转换成excel的验证格式，很不好处理，我刚才看看了google sheet 没有自定义的规则，应该也考虑到这个问题了

**Comment by yizhichenfamily** [comment]
还有关于第一个问题，若我不填能否将红色标记除去呢

**Comment by yizhichenfamily** [comment]
因为这样导致是必填项了

**Comment by myliang** [comment]
1 这个问题应该不存在，有考虑，我一会再好好看看

**Comment by yizhichenfamily** [comment]
存在这样的情况，因为我现在就卡在这里了

**Comment by myliang** [comment]
> 存在这样的情况，因为我现在就卡在这里了

x-data-spreadsheet@1.0.18 这个版本已经修复了，更新一下

**Comment by 1369220324** [comment]
现在可以导出excel了？

**Comment by yizhichenfamily** [comment]
> 现在可以导出excel了？
暂时是不行的

**Comment by yizhichenfamily** [comment]
关于数据输入后我再把数据删掉，在用getData方法获取数据的时候，会发现有空对象哦，请问一下能否将这种空对象删除掉，这样在我们处理数据的时候也轻松好多

**Comment by 1369220324** [comment]
自己稍微修改下data_proxy.js里面的getCellTextOrDefault()函数，或者自己写个新的，用在业务里面就好了

**Comment by myliang** [comment]
> 关于数据输入后我再把数据删掉，在用getData方法获取数据的时候，会发现有空对象哦，请问一下能否将这种空对象删除掉，这样在我们处理数据的时候也轻松好多

后面会考虑
