### ISSUE TITLE
复制粘贴，将spreadsheet里面的内容转化成excel的数据格式，粘贴出去

### ISSUE THREAD

**Issue by 1369220324** [myliang/x-spreadsheet#112]

**Comment by 1369220324** [comment]
或者可以把互相转化的公式有么？

**Comment by myliang** [comment]
> 或者可以把互相转化的公式有么？

这个需要先研究excel复制之后，系统剪切板里的存储格式.... 后续有时间我再看看

**Comment by 1369220324** [comment]
OK

**Comment by yoyomule** [comment]
这个功能比较有用，减少数据格式的重新设计，有些复杂的表格设计起来确实很麻烦，可以充分利用原有的excel表格，建议作者考虑。

**Comment by johnhemming** [comment]
I have done this using sheetjs and writing the x-s data structure into the sheetjs structure.

**Comment by yoyomule** [comment]
With sheetjs, can you keep the format and formula very well?

**Comment by johnhemming** [comment]
I am not having a problem with the formula.  The format, however, is a different issue and I have not tried to do anything with that as yet.   At the moment I am only really worried about the meaning of the spreadsheet and not the format once downloaded.

**Comment by johnhemming** [comment]
function convertXtoJS() {

    var wb = XLSX.utils.book_new();
    wb.Props = {Title: "Cashbook download",Subject: "Cash Book", Author: "Exedra", CreatedDate: new Date(2017,12,19) };
    ss = window.WEBPAGE.spreadSheet;

    for (sname in ss.sheet.worksheetList) {
    wkdata=ss.sheet.worksheetList[sname];    

    var jsvar = XLSX.utils.aoa_to_sheet([
        [""]]);

        var maxRow=1;
        var maxCol=1;
    for (row in wkdata.rows._)  {
    myrow=wkdata.rows._[row];    
    numRow=Number(row)+1;
    if (numRow>maxRow)maxRow=numRow;
    for (cell in myrow.cells) {
    mycell=myrow.cells[cell];
    numCell=Number(cell);
    if (numCell>maxCol)maxCol=numCell;

        ref=alphabet.stringAt(numCell)+numRow;

        console.log(ref+' '+cell+' '+numRow);
        if(mycell.text) {
        if (mycell.text[0]=='=') {
        jsvar[ref]={ t:'n', f:mycell.text};
        } else {
        if (isNaN(mycell.text)) {
        jsvar[ref]={ t:'s', v:mycell.text};
        }  else {
        jsvar[ref]={ t:'n', v:Number(mycell.text)};
        } 
        }}

    } } 
    jsvar['!ref']='A1:'+alphabet.stringAt(maxCol)+maxRow;
wb.SheetNames.push(sname);
wb.Sheets[sname] = jsvar;
    }

return wb;

}
