### ISSUE TITLE
版本更新之后，不能用了

### ISSUE THREAD

**Issue by zhouhuan0910** [myliang/x-spreadsheet#119]
![image](https://user-images.githubusercontent.com/22877154/56401504-ba795200-628b-11e9-9a8a-02698d31edf2.png)
你好，刚刚把版本升级到了最新的1.0.20，发现报了如上错误，猜测可能是数据结构变了导致，请问一下升级版本之后还兼容吗？需要做什么配置修改吗

**Comment by myliang** [comment]
我看看你的数据

**Comment by zhouhuan0910** [comment]
> 我看看你的数据

![image](https://user-images.githubusercontent.com/22877154/56410230-f70a7500-62ae-11e9-981a-6f84a9819ed9.png)

数据应该是没问题，后来发现是引入了语言包的问题
import zhCN from 'x-data-spreadsheet/dist/locale/zh-cn'
Spreadsheet.locale('zh-cn', zhCN)
如果不引入语言设置，则不会报错；但是升级之前是可以使用的，大概是意外发现了一个升级之后的问题吧

**Comment by myliang** [comment]
升级1.0.21,问题就解决了
之前没有build locale
