### ISSUE TITLE
Render expanded row with freeze rows will cause render problem

### ISSUE THREAD

**Issue by chardlau** [myliang/x-spreadsheet#123]

**Comment by chardlau** [comment]
I should have fixed this bug by myself. But i don't know how to...

Problem:
I expand row 7, and scroll up until the row 7 reach the freeze header rows. As the picture below shows, expanded row render un-properly.

![企业微信截图_ad99d91d-d0df-481d-ae81-479624071cc3](https://user-images.githubusercontent.com/20783716/56481058-a33a9e80-64ef-11e9-9ae0-caef16fa8084.png)

Reason:
See source file 'table.js'. function 'renderAll' and 'renderFreezeGridAndContent' render different cause the problem. 
Still see the picture above.
renderAll render row range "6,7,8,9...." which 7 is expanded
renderFreezeGridAndContent only see "8,9...." be cause i start with "fci + data.scroll.ci".  No row is expanded here.

**Comment by myliang** [comment]
update your locale code

**Comment by chardlau** [comment]
renderContentGrid  sumWidth is not defined

**Comment by myliang** [comment]
update lastest version

**Comment by chardlau** [comment]
It works. Thank you.
