### ISSUE TITLE
单元格合并之后向下滚动滚动条，样式和内容就消失了，该怎么调呢

### ISSUE THREAD

**Issue by ltt201894** [myliang/x-spreadsheet#126]
![image](https://user-images.githubusercontent.com/39078242/56650799-5d7e0180-66ba-11e9-8fe8-be41cfa48f98.png)
![image](https://user-images.githubusercontent.com/39078242/56650826-6a9af080-66ba-11e9-9656-c31fb177d924.png)

**Comment by myliang** [comment]
请确认你当前使用的是否是最新版本

**Comment by ltt201894** [comment]
是最新版本，我是拿你写的demo测试的，在index.html中的loadData函数中加入了数据，然后单元格merge的区域在出现滚动条之后就会消失，
![image](https://user-images.githubusercontent.com/39078242/56703522-d70a0400-673b-11e9-8d7f-ed044f0bb6b1.png)
