### ISSUE TITLE
能否支持与excel的双向复制粘贴功能

### ISSUE THREAD

**Issue by bxfxf** [myliang/x-spreadsheet#129]
请问是否有计划支持与excel的双向复制粘贴功能？可以参考下handsontable

**Comment by myliang** [comment]
暂时还没有这个计划，如果要实现也只能是复制内容

**Comment by Vinnie2689** [comment]
这个功能现在有计划吗

**Comment by myliang** [comment]
> 这个功能现在有计划吗

只能复制文本，其实这个功能就是导入导出，导入导出可以后台转换
