### ISSUE TITLE
怎么让scrollbar 常驻显示

### ISSUE THREAD

**Issue by lishihong** [myliang/x-spreadsheet#134]
怎么让scrollbar 常驻显示

**Comment by myliang** [comment]
可以css样式修改，后面会修改为一直显示

**Comment by lishihong** [comment]
大佬，问一个问题，我们现在有个需求，点击某列，可以更改某列的背景色，怎么把某列的点击事件接口方法给暴露出来？

**Comment by myliang** [comment]
点击莫烈，还是某个单元格，现在点击整列背景色是变化的
