### ISSUE TITLE
千万级数据显示怎么优化？

### ISSUE THREAD

**Issue by lishihong** [myliang/x-spreadsheet#136]
我们这么要显示一个10000*8000列左右的数据，我测试了下，最多显示4000行，700列数据就内存溢出了，有优化方案吗

**Comment by myliang** [comment]
700 列　8000 列　太夸张了吧

**Comment by myliang** [comment]
暂时没有考虑类似问题

**Comment by lishihong** [comment]
是这样的，用户需求是这样，和simca功能比较像，要分析所有因子

**Comment by myliang** [comment]
Excel也没有用700列吧
可以试一试几十列 万行
