### ISSUE TITLE
json 传进去1000多行数据,为什么只能显示前100行?有行数上限吗?

### ISSUE THREAD

**Issue by theFish001** [myliang/x-spreadsheet#147]
如题

**Comment by myliang** [comment]
rows.len = 1000

**Comment by theFish001** [comment]
最大支持多少行？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yuliang.liang <notifications@github.com>
发送时间: 2019年5月29日 21:58
收件人: myliang/x-spreadsheet <x-spreadsheet@noreply.github.com>
抄送: theFish001 <1149744713@qq.com>, Author <author@noreply.github.com>
主题: 回复：[myliang/x-spreadsheet] json 传进去1000多行数据,为什么只能显示前100行?有行数上限吗? (#147)




rows.len = 1000

**Comment by myliang** [comment]
理论上没有限制，看浏览器内存

**Comment by theFish001** [comment]
好的  ，谢谢！！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yuliang.liang <notifications@github.com>
发送时间: 2019年5月29日 22:18
收件人: myliang/x-spreadsheet <x-spreadsheet@noreply.github.com>
抄送: theFish001 <1149744713@qq.com>, Author <author@noreply.github.com>
主题: 回复：[myliang/x-spreadsheet] json 传进去1000多行数据,为什么只能显示前100行?有行数上限吗? (#147)




理论上没有限制，看浏览器内存

**Comment by theFish001** [comment]
已经改成1000，但是好像不起效果，什么原因？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yuliang.liang <notifications@github.com>
发送时间: 2019年5月29日 21:58
收件人: myliang/x-spreadsheet <x-spreadsheet@noreply.github.com>
抄送: theFish001 <1149744713@qq.com>, Author <author@noreply.github.com>
主题: 回复：[myliang/x-spreadsheet] json 传进去1000多行数据,为什么只能显示前100行?有行数上限吗? (#147)




rows.len = 1000

**Comment by theFish001** [comment]
问题已经解决了，感谢大神的开源项目，谢谢！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yuliang.liang <notifications@github.com>
发送时间: 2019年5月30日 08:40
收件人: myliang/x-spreadsheet <x-spreadsheet@noreply.github.com>
抄送: theFish001 <1149744713@qq.com>, Author <author@noreply.github.com>
主题: 回复：[myliang/x-spreadsheet] json 传进去1000多行数据,为什么只能显示前100行?有行数上限吗? (#147)




Closed #147.
