### ISSUE TITLE
超过100行之后就不能保存了

### ISSUE THREAD

**Issue by giveahug** [myliang/x-spreadsheet#151]
![image](https://user-images.githubusercontent.com/34709078/58847039-081f1200-86b4-11e9-8ea7-690c3f06405a.png)

我录了100多行，只有前100行才保存得了

**Comment by myliang** [comment]
需要 loadData({
  rows: { len: 1000 }
})
你先录入多少就把这个len设置多少

**Comment by giveahug** [comment]
> {
> rows: { len: 1000 }
> }

那要渲染的excel数据比如data对象要放在哪里，是这样吗
x.spreadsheet('#xspreadsheet')
            	.loadData(data，{
rows: { len: 1000 }
}).change(data => {
});

**Comment by giveahug** [comment]
可是一点作用都没有起到

**Comment by giveahug** [comment]
我发现问题了，1.0.23版本下这样写可以，并且横纵坐标都成功的可以自定义长度了
![image](https://user-images.githubusercontent.com/34709078/58857732-8097ca00-86d8-11e9-907b-9cf07f79abe8.png)
![image](https://user-images.githubusercontent.com/34709078/58857840-ba68d080-86d8-11e9-8b75-f1b8c5bc62a2.png)

更新到1.0.24版本就跑异常了
const options = {
                	showToolbar: false
                };
                
            	x.spreadsheet('#xspreadsheet',options)
            	.loadData(body)
            	.change(data => {
            		console.log(data)

            	});
![image](https://user-images.githubusercontent.com/34709078/58857940-f9972180-86d8-11e9-8e99-49241eb0cee3.png)

**Comment by myliang** [comment]
```javascript
.loadData({
          rows: {
　　　 len: 1000
            1: {
              cells: {
                0: { text: 'testingtesttestetst' },
                2: { text: 'testing' },
              },
            },
            2: {
              cells: {
                0: { text: 'render-nihaodewo de peynwo' },
                1: { text: 'Hello' },
                2: { text: 'hahahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh' },
              }
            },
            8: {
              cells: {
                8: { text: 'border test', style: 0 },
              }
            }
          },
        });
```
