### ISSUE TITLE
demo 上列表不出现滚动条

### ISSUE THREAD

**Issue by ibmsoft** [myliang/x-spreadsheet#152]
打开 demo 展示页

https://myliang.github.io/x-spreadsheet/

然后，右键增加 列，然后不出现左右滚动条，只有当在单元格上按 tab 键，才能出现新增加的这列

**Comment by myliang** [comment]
demo没有更新， 下载本地看最新效果

**Comment by ibmsoft** [comment]
拉代码跑也是一样的

**Comment by myliang** [comment]
是苹果系统吗？macos下有点问题

**Comment by ibmsoft** [comment]
对，macos

**Comment by myliang** [comment]
> 对，macos

拉一下代码，看一下效果，我修改了一下
