### ISSUE TITLE
请教：如何通过js设置单元格的值？谢谢

### ISSUE THREAD

**Issue by tao518** [myliang/x-spreadsheet#170]
如题 ，sheet加载数据后，想通过js设置某个单元格的值
注：老大有没有微信群或QQ群呢？

**Comment by tao518** [comment]
已通过重新Load实现~ 不知道会不会有效率问题

**Comment by myliang** [comment]
这个数据应该是你程序后台拼好，直接load的，不知道主要用作什么（当表格使用。。）

**Comment by gezi666** [comment]
大佬能不能开放出来针对单元格操作的API，我们是想通过API自己去操作单元格，而不是通过后台提供的data是直接load的

**Comment by myliang** [comment]
> 大佬能不能开放出来针对单元格操作的API，我们是想通过API自己去操作单元格，而不是通过后台提供的data是直接load的

这个单元格的画布上上去的，开发出来对于普通的html操作没用的
