### ISSUE TITLE
可以通过API操作表格滚动吗

### ISSUE THREAD

**Issue by Mr-Fxiansheng** [myliang/x-spreadsheet#171]
您好，

想操作表格滚动，同时滚动条的位置与表格显示内容的位置保持同步。

**Comment by myliang** [comment]
有这样的需求？

**Comment by Mr-Fxiansheng** [comment]
数据很多的时候，一页是展示不下的，会出现滚动条。想要让它按照一定的间隔时间自动往下滚动，到最后的时候在从最上面开始重复。

**Comment by myliang** [comment]
用户自己滚动岂不是更好

**Comment by Mr-Fxiansheng** [comment]
表格内容需要投到大屏上，实际是不操作的。
源码里面，我看有scrollx、scrolly这样的API，也就是表格是有滚动的，我是有点不知道怎么用。至于怎么实现自动滚动我可以想办法处理。

**Comment by myliang** [comment]
这是内部的api，对外的没有滚动的接口

**Comment by Mr-Fxiansheng** [comment]
就是说，如果要支撑我的需求，没有办法了对吗？

**Comment by myliang** [comment]
是的，但是你可以现在源码二次开发，随便你怎么修改都行

**Comment by Mr-Fxiansheng** [comment]
嗯嗯，好的，非常感谢。
