### ISSUE TITLE
version 1.0.24 mac os系统中,只能上下滑动, 左右不能滑动

### ISSUE THREAD

**Issue by Hyg900928** [myliang/x-spreadsheet#172]
只能看到第N列, 后面的列数, 只能通过一直按Tab键,才能一个个的显示出来
我用的是mac系统, chrome 浏览器, 请问这是什么原因呢?
![image](https://user-images.githubusercontent.com/19190553/61392431-5ea58000-a8f1-11e9-8cef-38805389787b.png)

**Comment by myliang** [comment]
兼容性问题 暂时没环境 你可以拉个分支解决下

**Comment by myliang** [comment]
有滚动条可以滚动

**Comment by Hyg900928** [comment]
@myliang 你所说的兼容性问题, 是指系统的兼容性, 还是指浏览器的兼容性啊, 还有,我并没有看到有滚动条 ,是需要我自己做吗?

**Comment by Hyg900928** [comment]
不好意思, 我看到滚动条了, 昨天怎么就没有呢, 好奇怪啊

**Comment by bbandydd** [comment]
@Hyg900928 @myliang 
不好意思，我也是mac os，一样没有看到滚动条，请问该怎么解决呢？
