### ISSUE TITLE
能否设置隐藏掉行头和列头

### ISSUE THREAD

**Issue by wjxkkxx** [myliang/x-spreadsheet#175]
这边想隐藏掉行头和列头，类型grid一样去展现内容有没有办法设置

**Comment by myliang** [comment]
暂时没有办法，需要修改渲染代码

**Comment by wjxkkxx** [comment]
谢谢回复，那后续可以加一个配置参数来关闭显示吗。并且可以考虑增加点击事件的响应吗

**Comment by myliang** [comment]
你是想怎么使用，用在什么地方，是否着急，如果你对代码熟悉可以二次开发，暂时代码大框架不会修改

**Comment by wjxkkxx** [comment]
简单来说，我需要做一个将excel内容在前台展示的功能，但是仅仅是展示，不可编辑，也不需要行头列头类似一个grid,然后可能会通过点击某个单元格展示一些其他内容。着急到不是太着急。如果可以的话可否介绍一下相关代码的位置，我可以自己二次调整。

**Comment by myliang** [comment]
那你还看看代码直接修改吧，代码比较易懂

**Comment by wjxkkxx** [comment]
好吧，谢谢您的帮助
