### ISSUE TITLE
调整列宽-触发change事件

### ISSUE THREAD

**Issue by tao518** [myliang/x-spreadsheet#189]
大神你好，能不能加入 调整列宽触发change事件呢？或者怎么加？ 谢谢

**Comment by myliang** [comment]
可以在sheet.js文件中自己添加
具体代码如下
![image](https://user-images.githubusercontent.com/718858/63830617-2c327c80-c99f-11e9-84e8-cdbcbb72fc63.png)

**Comment by tao518** [comment]
非常感谢~
