### ISSUE TITLE
隐藏行、隐藏列

### ISSUE THREAD

**Issue by gezi666** [myliang/x-spreadsheet#190]
大佬后续有没有计划添加隐藏行、隐藏列功能

**Comment by myliang** [comment]
会考虑的

**Comment by gezi666** [comment]
目前的架构是不是得动？
感觉把行隐藏了，好多功能都有异常……
希望这个功能能早日开发出来。




------------------ 原始邮件 ------------------
发件人: "yuliang.liang"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午10:21
收件人: "myliang/x-spreadsheet"<x-spreadsheet@noreply.github.com>;
抄送: "每一天"<3129168699@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [myliang/x-spreadsheet] 隐藏行、隐藏列 (#190)




会考虑的

**Comment by myliang** [comment]
渲染代码得修改，最近没时间处理这些，你要着急可以自己修改代码，代码比较易懂
