### ISSUE TITLE
spreadsheet 的ctrl+c 复制内容  没有到粘贴板的嘛

### ISSUE THREAD

**Issue by zybieku** [myliang/x-spreadsheet#225]
spreadsheet 内容 复制没有复制到粘贴板的嘛,我从一个窗口复制内容 ,发现到另外一个窗口粘贴板根本没有内容,同一个sheet里面可以 

同一个 
![image](https://user-images.githubusercontent.com/15903330/68203742-7409fb80-0001-11ea-906d-d591dff66de8.png)

 不同spreadsheet 就不行,sheet1无法复制到sheet2
![image](https://user-images.githubusercontent.com/15903330/68203978-f5618e00-0001-11ea-9d1f-912fde41788b.png)

就是我想重写覆盖应该怎么弄 有复制 粘贴的钩子函数嘛

**Comment by zybieku** [comment]
或者说 我想要获取 我选择的内容,选择复制的时候 可以复制到粘贴板上, s
preadSheet默认实现的ctrl+C没有的, 有ctrl+c的钩子回调嘛,把复制的内容暴露出来;
实在不行,给我一个我选择区域的钩子回调也行

**Comment by myliang** [comment]
看源码，二采开发自己添加这个功能就行了，应该不是太复杂

**Comment by zybieku** [comment]
大佬 看不懂 玩不来

**Comment by myliang** [comment]
研究下，如果你要在生产环境使用还是需要二次开发的

**Comment by myliang** [comment]
代码比较简单易懂

**Comment by zybieku** [comment]
大佬 大佬 求放过 我以前是个弄JAVA 安卓的 人生中都没有项目 超过 star 1000的,搞vue不长, 对JS这块 涉猎皮毛,赶鸭子上架才临时要弄一个文档的项目,   二次开发特么就没那么大的精力了,最起码最近木有,只是觉得大佬的东西 ,修改一个钩子相对较快,要是大佬木有精力维护的话  我也只能在不改这个库的前提下 重写监听了

**Comment by myliang** [comment]
暂时没有时间修改。。

**Comment by zybieku** [comment]
看了大佬的代码确实,自己二次确实容易拓展自己需要钩子,膜拜大佬

**Comment by liuhengguang** [comment]
> 
> 
> 看了大佬的代码确实,自己二次确实容易拓展自己需要钩子,膜拜大佬



> 
> 
> 看了大佬的代码确实,自己二次确实容易拓展自己需要钩子,膜拜大佬

你好呀，请问解决这个问题了吗？能否给些提示呢？多谢~

**Comment by zybieku** [comment]
下载作者的源码，自己改就好了

hengguang liu <notifications@github.com> 于 2020年8月10日周一 15:13写道：

**Comment by cxwSuperman** [comment]
研究了一下，膜拜大佬+1
