### ISSUE TITLE
Get data in cell / tracking highlighted cell / events on cells

### ISSUE THREAD

**Issue by Tisoy21** [myliang/x-spreadsheet#227]
how can i specify each cell selected, and track what column / rows highlighted ? is there any method to use ? any help would appreciated thanks

**Comment by CMarry** [comment]
您好，我想问一下您的问题解决了吗？

**Comment by Tisoy21** [comment]
not yet, i use react js as a framework

**Comment by krishnakprakash** [comment]
How can i get all the data of highlighted/selected cells. I see an event **cells-selected** but it gives me only the last column value. How to get the array of selected items?

**Comment by HondryTravis** [comment]
data.getSelectedCell() in src/core. @krishnakprakash

**Comment by krishnakprakash** [comment]
@HondryTravis i tried to access this method from instance of spreadsheet but ended up with getting null. I am using it within the "cells-selected" event listener. please correct me if i am doing something wrong

`
// spr is the x-data-spreadsheet instance
spr.on('cells-selected', (cells, { sri, sci, eri, eci }) => {
        console.log(spr.data.getSelectedCell());
        console.log('cell:', cells, ', sri:', sri, 'sci:', sci, 'eri:', eri, 'eci:', eci );
      })
`

**Comment by HondryTravis** [comment]
@krishnakprakash  you want get all selected cell ?

**Comment by HondryTravis** [comment]
you can used this way：

```javascript
// xs instance
// this range  is you selected area , all selected cell in this one
const { range } = xs.sheet.data.selector
// then you can do this used xs.sheet.data.rows.getCell(ri, ci) and push one array, this array is you want result
```
![image](https://user-images.githubusercontent.com/24218012/112411604-27d76c80-8d58-11eb-8da6-804ca0685e96.png)

**Comment by HondryTravis** [comment]
Or join we [Community](https://github.com/HondryTravis/xs-docs/blob/master/README.md) @krishnakprakash
