### ISSUE TITLE
建议selector选中框显示使用  box-sizing

### ISSUE THREAD

**Issue by zybieku** [myliang/x-spreadsheet#228]
集成x-spread  发现选中selector右下会有2px间隙
![image](https://user-images.githubusercontent.com/15903330/68366384-265ed180-016e-11ea-9f0b-286f3bdf3246.png)
而大佬的demo没有,
发现原因 是大佬使用默认的content-box盒子模型,而一般我们在集成项目的时候可能会重置base,修改盒子为boder-box. 导致默认模型覆盖了
建议大佬的index.less 的selector 显示使用盒子模型,这样就不会被覆盖
![image](https://user-images.githubusercontent.com/15903330/68366676-e0eed400-016e-11ea-8a24-eb9cb9867fc8.png)

**Comment by myliang** [comment]
如果上线使用，建议你们自己二次开发，当然现有功能能满足也可以就这样用
