### ISSUE TITLE
老铁，有没有注销的api？

### ISSUE THREAD

**Issue by zc1789284658** [myliang/x-spreadsheet#232]
单页面应用，需要同一个div先后加载行列数不同的spreadsheet（改了下源码，把row.len和col.len作为参数传进去了），我这边直接把div内innerHTML全部清除重新loadData，会出现内存泄露的问题

或者有没有方法可以在loadData后，change row.len和col.len

**Comment by myliang** [comment]
loadData 参数里就可以设置

**Comment by zc1789284658** [comment]
wow~ ⊙o⊙ 
我看着是只有new SpreadSheet的时候才能传` settings:{row:{len:99},col:{len:99}}`

已经初始化过的，后面loadData的时候也能传么？

还是说loadData可以注销当前的spread另外加载一个row.len和col.len不同的表？

**Comment by myliang** [comment]
可以传
