### ISSUE TITLE
how  to fire click event on a cell,  如何触发点击事件

### ISSUE THREAD

**Issue by dev-1603** [myliang/x-spreadsheet#237]
unable to fire click event in an cell to get sub cell

**Comment by CMarry** [comment]
@dev-1603 您好，我想问一下您的问题解决了吗？解决了的话可以告诉我一下吗

**Comment by dev-1603** [comment]
hey Myliang/X-Spreadsheet,
 i  want to know  , if i can change the   title of the column  i.e i want
to put custom names for the columns instead of A,B,C

[image: xspreadsheet column name .jpg]

will be waiting for your reply ,
Thank you

*Debjyoti Mohapatra*

**Comment by myliang** [comment]
> hey Myliang/X-Spreadsheet, i want to know , if i can change the title of the column i.e i want to put custom names for the columns instead of A,B,C [image: xspreadsheet column name .jpg] will be waiting for your reply , Thank you *Debjyoti Mohapatra*

need to change resource code
