### ISSUE TITLE
multiple sheet ?

### ISSUE THREAD

**Issue by Tisoy21** [myliang/x-spreadsheet#238]
is it supported on multiple spreadsheet in one project ? any help would be appreciated thanks

**Comment by myliang** [comment]
sorry

**Comment by rubennaatje** [comment]
You mean like tabs? Don't think so but depending on what you use it in you should be able to do it yourself pretty easily.

**Comment by Tisoy21** [comment]
yes like the tabs per sheet 
<img width="604" alt="Screen Shot 2019-11-28 at 3 46 18 AM" src="https://user-images.githubusercontent.com/44186119/69754917-0bdaaf80-1192-11ea-981b-57ee9501fada.png">

u already made it ? @rubennaatje

**Comment by rubennaatje** [comment]
Nope but I might do it in the future, really love this project by @myliang.

**Comment by Tisoy21** [comment]
ok tnx, maybe the tabs can do by bootstrap tabs

**Comment by CMarry** [comment]
@Tisoy21  你这个功能实现了吗？

**Comment by Tisoy21** [comment]
@CMarry Not yet

**Comment by myliang** [comment]
fixed, update
