### ISSUE TITLE
大佬请问怎么进行二次开发

### ISSUE THREAD

**Issue by ligengdipan** [myliang/x-spreadsheet#240]
增加工具栏或者其他功能

**Comment by ligengdipan** [comment]
有没有文档，看到这个项目很棒，但是想使用不知道从哪儿下手，入增加工具栏，自定义公式，表头冻结等。

**Comment by myliang** [comment]
二次开发，读源码，代码比较易懂

**Comment by ligengdipan** [comment]
抱歉可能是我没看懂，我看spredsheet.js是压缩的，如何进行二次开发请告知一下，谢谢了

**Comment by myliang** [comment]
src目录下就是源码？？？

**Comment by ligengdipan** [comment]
谢谢大佬，我搞明白了,原来是webpack打包的。
