### ISSUE TITLE
#中文输入问题# Question: Chinese input bug

### ISSUE THREAD

**Issue by HondryTravis** [myliang/x-spreadsheet#246]
你好，这个excel每次输入中文第一个字符总是单独的字母，而不是拼音输入的拼音连接词，像这样
c e'shi默认c 是第一个字母而不是在拼音中。

**Comment by leehom0123** [comment]
五笔输入法表示也有这个问题

**Comment by Junran777** [comment]
i also meet the same question, when not double click sheet, just click the sheet and use chinese input, same problem will come up

**Comment by Junran777** [comment]
and excel or Tencent sheet don' t have that problem

**Comment by ghost** [comment]
这么说, 这个项目还是抄袭国外的? 这是国外软件的通病.
