### ISSUE TITLE
大佬，行高设置为0无效，0.001就有效，但是会影响到滚动条

### ISSUE THREAD

**Issue by HondryTravis** [myliang/x-spreadsheet#248]

**Comment by myliang** [comment]
为什么要设置为0

**Comment by HondryTravis** [comment]
@myliang 想想做隐藏，和展示，但是会影响到很多东西，很多地方都要重构，然后想到exceptRow和excepColum排除，但是发现有有很多地方都要重新计算。直接 设置为0是比较快的 : (

**Comment by myliang** [comment]
这个确认需要改很多东西

**Comment by HondryTravis** [comment]
@myliang 我有尝试过重构部分代码，但是耦合度比较高，隐藏行列几乎涉及到大部分功能都有问题。

**Comment by HondryTravis** [comment]
不过周末已解决部分问题

**Comment by myliang** [comment]
已经支持行列隐藏功能
