### ISSUE TITLE
Create internationalization (i18n) translations

### ISSUE THREAD

**Issue by daltondiaz** [myliang/x-spreadsheet#25]
Create i18n feature for future translations.

**Comment by xam4lor** [comment]
How about creating a folder with some files in it. When the user "load" the code on the index.html file, he passes a parameter called 'language' (default EN), and the code just load the corresponding file.

**Comment by xam4lor** [comment]
For example like the following structure :

In 'index.html' : 
```
[...]
.loadData({
  language : 'EN'
})
[...]
```

And the code just check the file in `src/language/EN.json` and load it into a global constant object like 'LANGUAGE'.
To get a text, we just need to do a `LANGUAGE.get(_id)` to get the corresponding string.

**Comment by xam4lor** [comment]
Check [my modification test](https://github.com/xam4lor/x-spreadsheet/commit/b9ad2d513556e07f90076c147272307f8d47a44a).

**Comment by daltondiaz** [comment]
> Check [my modification test](https://github.com/xam4lor/x-spreadsheet/commit/b9ad2d513556e07f90076c147272307f8d47a44a).

Its ok for me!

Create a PR!!

**Comment by xam4lor** [comment]
Done! Check #48.

**Comment by myliang** [comment]
wiki: https://github.com/myliang/x-spreadsheet/wiki/Internationalization
