### ISSUE TITLE
多表的数据监听事件

### ISSUE THREAD

**Issue by wxyer** [myliang/x-spreadsheet#261]
单表没有问题，当有两个表的时候，change事件 只提示表1，表2的数据更改事件忽略了。

**Comment by wxyer** [comment]
还有一个中文本地化的bug 底部的bottombar 右键删除的文字是空白的，不适用zh-cn语言的话，显示是delete

**Comment by myliang** [comment]
change就是当前编辑的sheet

**Comment by wxyer** [comment]
> change就是当前编辑的sheet

那多表的话，可能是我使用有问题 这是我的代码

 Spreadsheet.locale('zh-cn', zhCN);
    new Spreadsheet(document.getElementById('spreadsheet'),
      {
        showToolbar: true,
        showGrid: true,
        showContextmenu: true
      })
      .loadData(this.data) // load data
      .change((data: any) => {
        console.log(data);
      });

再界面底部的工具栏增加一个sheet2，然后再sheet2里面增加内容，change事件没有响应

**Comment by myliang** [comment]
https://github.com/myliang/x-spreadsheet/wiki/Internationalization

**Comment by wxyer** [comment]
> https://github.com/myliang/x-spreadsheet/wiki/Internationalization

多谢大佬 我翻了下源码 中文的相应文字没有缺，可能是其他地方的问题把
