### ISSUE TITLE
The "name" property of a sheet is now mandatory

### ISSUE THREAD

**Issue by alexsegura** [myliang/x-spreadsheet#279]
This was introduced in 488e5ed880109ba52826730b23d0085bde170133

When using `loadData`, if a sheet has no `name` property, it fails with the following error

```
Uncaught TypeError: 
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'
```

This is a BC break, as sheets without names used to work before.

**Comment by alexsegura** [comment]
Thank you @myliang

**Comment by Nihal-Chandwani** [comment]
im still getting this error

`import React from 'react';
import Spreadsheet from 'x-data-spreadsheet';
const SchoolSheet = () => {
  // If you need to override the default options, you can set the override
  // const options = {};
  //   new Spreadsheet('#x-spreadsheet-demo', options);
  const s = new Spreadsheet('#xspreadsheetdemo', {})
    .loadData([
      {
        name: 'sheet-test-1',
        freeze: 'B3',
        styles: [
          {
            bgcolor: '#f4f5f8',
            textwrap: true,
            color: '#900b09',
            border: {
              top: ['thin', '#0366d6'],
              bottom: ['thin', '#0366d6'],
              right: ['thin', '#0366d6'],
              left: ['thin', '#0366d6'],
            },
          },
        ],
        merges: ['C3:D4'],
        rows: {
          1: {
            cells: {
              0: { text: 'testingtesttestetst' },
              2: { text: 'testing' },
            },
          },
          2: {
            cells: {
              0: { text: 'render', style: 0 },
              1: { text: 'Hello' },
              2: { text: 'haha', merge: [1, 1] },
            },
          },
          8: {
            cells: {
              8: { text: 'border test', style: 0 },
            },
          },
        },
      },
      { name: 'sheet-test' },
    ]) // load data
    .change((data) => {
      console.log(data);
      // save data to db
    });

  // data validation
  //   s.validate();

  return (
    <>
      <div id="xspreadsheetdemo"></div>
    </>
  );
};

export default SchoolSheet;`


Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
