### ISSUE TITLE
配置了公式后，在公式前上方插入行列，公式能够自动适应吗

### ISSUE THREAD

**Issue by Jkarel** [myliang/x-spreadsheet#285]
大神，你好，我在试用的时候遇到这个问题，比如在C7单元格设置了公式=SUM(C1:C6)， 然后在C1上方插入一行，公式能自动适应变成=SUM(C2:C7)吗。

**Comment by myliang** [comment]
这个你自己修改源码

**Comment by Jkarel** [comment]
好的，感谢回复
