### ISSUE TITLE
Row Insert doesn't update cell positions

### ISSUE THREAD

**Issue by codecourse-cc** [myliang/x-spreadsheet#315]
Hi,

Row Insert or similar actions doesn't update the cell position.

Example:
=A2+B2 
After Insert row before Row 2, the function needs to be updated but the cell keeps the same one as before. It should be A3+B3.

When we add/remove row/col then these actions should update cell positions as well.

Thanks

**Comment by HondryTravis** [comment]
u should use the correct function, example =SUM(A2, B2)

**Comment by codecourse-cc** [comment]
@HondryTravis, no predefined functions work too.
![demo](https://user-images.githubusercontent.com/60815071/84231899-3b368580-ab00-11ea-99a8-6e2843e1e1e7.gif)

**Comment by azal-io** [comment]
Function below adds new row, as you can see it check row index and if >= than selected row index then it just change the nri or new row index and then just adds the row data to new index.

I think there should be additional check to see if there are references then those references to cells should be updated with new index, like A1 in this case should be A2.

This goes with insertColumn too it needs to check if there are references to cells then cells should go from A1 to B1 lets say.

```
// x-spreadsheet/src/core/row.js#209
insert(sri, n = 1) {
  const ndata = {};
  this.each((ri, row) => {
    let nri = parseInt(ri, 10);
    if (nri >= sri) {
      nri += n;
    }
    ndata[nri] = row;
  });
  this._ = ndata;
  this.len += n;
}
```

**Comment by azal-io** [comment]
**Does anyone check these issues?**

**Comment by azal-io** [comment]
@myliang Why are you closing the issue? It has not been solved yet.

The common logic is that when you remove/add rows/columns it should update the positions as well. And current implementation does not.

Thanks

**Comment by azal-io** [comment]
@myliang Thanks a lot. I just checked, it works wonderfully.
