### ISSUE TITLE
Delete button not working in mac

### ISSUE THREAD

**Issue by sain2424** [myliang/x-spreadsheet#32]
Not able to delete cell

**Comment by sain2424** [comment]
OS: Mac
Browser: Firefox

Also delete button goes back to previous page sometimes.

**Comment by myliang** [comment]
Please update the latest version

**Comment by shunia** [comment]
The demo could be updated too maybe.`Delete` key not working in the demo page for now.

**Comment by myliang** [comment]
it is ok at present

**Comment by sain2424** [comment]
fixed

**Comment by shunia** [comment]
Demo is still not working.

**Comment by sain2424** [comment]
maybe setup CI for demo? @myliang

**Comment by myliang** [comment]
update demo after my vacation
