### ISSUE TITLE
x-spreadsheet可以扩展字段拖拽效果么？

### ISSUE THREAD

**Issue by brianzhang** [myliang/x-spreadsheet#325]
![vtMS-_yeaM62cbJM6iS9ktog](https://user-images.githubusercontent.com/766999/85279323-d6443d80-b4b8-11ea-9ecd-5fbbcb463d43.gif)
类似这样的交互效果，表格内的字段需要动态设置

**Comment by duduhey** [comment]
我也准备扩展下拖拽这块，不过没你的复杂，只需要实现简单的数字递增就好

**Comment by brianzhang** [comment]
> 我也准备扩展下拖拽这块，不过没你的复杂，只需要实现简单的数字递增就好

能拖拽过去么？你的拖拽方式怎么实现的呢？

我在React中使用的DND

**Comment by brianzhang** [comment]
已通过另外一个方式实现该效果

**Comment by wen81643956** [comment]
> 已通过另外一个方式实现该效果

大佬，请问下怎么实现的。能提供下思路吗。我们刚好也要做这个功能

**Comment by llearn** [comment]
> 已通过另外一个方式实现该效果

请问怎么解决的呢？

**Comment by Xxxdxs** [comment]
> 已通过另外一个方式实现该效果

能讲一下实现原理嘛?

**Comment by Bale123** [comment]
> ![vtMS-_yeaM62cbJM6iS9ktog](https://user-images.githubusercontent.com/766999/85279323-d6443d80-b4b8-11ea-9ecd-5fbbcb463d43.gif) [ ![vtMS-_yeaM62cbJM6iS9ktog](https://user-images.githubusercontent.com/766999/85279323-d6443d80-b4b8-11ea-9ecd-5fbbcb463d43.gif) ](https://user-images.githubusercontent.com/766999/85279323-d6443d80-b4b8-11ea-9ecd-5fbbcb463d43.gif) [ ](https://user-images.githubusercontent.com/766999/85279323-d6443d80-b4b8-11ea-9ecd-5fbbcb463d43.gif) 类似这样的交互效果，表格内的字段需要动态设置

大佬这个效果实现了吗？我们搞好也有这需求，react的库。能给点参考吗？

**Comment by NickHi** [comment]
同问，如何实现
