### ISSUE TITLE
font 的underline可以支持么,还有strikout 设置了没有效果，设置了导出data或者load的时候设置了strikout都没有效果

### ISSUE THREAD

**Issue by difeijin** [myliang/x-spreadsheet#355]
font 的underline可以支持么,还有strikout 设置了没有效果，设置了导出data或者load的时候设置了strikout都没有效果

**Comment by difeijin** [comment]
1underline support
2strikout support

**Comment by HondryTravis** [comment]
{
strike: boolean,
underline: boolean
}
