### ISSUE TITLE
Typo: "a javascript spreadsheet for web"

### ISSUE THREAD

**Issue by shlomif** [myliang/x-spreadsheet#42]
It should be "A web-based JavaScript spreadsheet". Appears twice in the front page.

**Comment by sain2424** [comment]
this is fixed

**Comment by shlomif** [comment]
On Mon, 04 Feb 2019 09:53:23 +0000 (UTC)
Sain <notifications@github.com> wrote:

> this is fixed
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Apple Inc. is Evil - http://www.shlomifish.org/open-source/anti/apple/

Yesterday I asked one of my students if she knew what an encyclopedia is, and
she said: “Is it something like Wikipedia?”.
        — http://twitter.com/alisonclement/status/8421314259

Please reply to list if it's a mailing list post - http://shlom.in/reply .
