### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by MartinDawson** [myliang/x-spreadsheet#461]
Hi,

Firs of all this is an amazing project with great UI and speed.

However this project has been semi-abandoned basically and maintenance of it has sadly not kept up with it.

I would like to request to become a maintainer of this project for the community and implement bug fixes/features.

Currently, I have fixed quite a few of the issues in my own private fork of this repository maintained for my own website here: https://tracktak.com

The big issue with this project is the settings of features programmatically and not just on initialization which I can fix and the structure of the code needs converting from classes to functions/objects to stop inheritance hell.

We have the time to maintain this project for the community as we use it ourselves for our site.

I will also email you directly with this.

Thanks

**Comment by myliang** [comment]
you can pull requests

**Comment by MartinDawson** [comment]
@myliang I'm not going to waste time doing pull requests and raising issues when there are over 212 open issues already and pull requests just left for dead with 0 comments or replies on them.

This is why this project has over 1.2k forks. Because it isn't being maintained well enough.
