### ISSUE TITLE
New method to get the data of the spreadsheet

### ISSUE THREAD

**Issue by xavierfaucon** [myliang/x-spreadsheet#51]
What would you recommend to get the all the data of the spreadsheet as one object without a change event?

I see two methods in the Spreadsheet class: loadData and change.
Could we use a new method "getData" or there's already a way to do that?

**Comment by myliang** [comment]
```javascript
// all the data of the spreadsheet
const data = {};
x.spreadsheet('#x-data-spreadsheet').loadData(data);

```

**Comment by xavierfaucon** [comment]
Ok thank you for your reply. It works well that way. 
How would you have done to read the data if the spreadsheet was initialized without
`const data = {};`

Maybe it could be added in the documentation how to programmatically read and write data.

**Comment by myliang** [comment]
write data: loadData
read data: change(data) or getData()
