### ISSUE TITLE
 a bug

### ISSUE THREAD

**Issue by wangzhedong** [myliang/x-spreadsheet#56]
当文字的长度超过了单元的宽度，点击文本对齐的居中，或者居右，会出现文字溢出到左边单元格的情况，这个怎么解决？

**Comment by wangzhedong** [comment]
draw.js  222 line
add code:
substring the text
  if(txtWidth > box.innerWidth() && align != 'left'){
      let singleTxtDpr = txtWidth/txt.length;
      let overCellDpr = txtWidth-box.innerWidth();
      let txtCount = Math.round(overCellDpr/singleTxtDpr);
      txt = txt.substring(txtCount,txt.length);
    }

**Comment by myliang** [comment]
等我重构一下核心代码，再修改这个问题

**Comment by wangzhedong** [comment]
我们这边项目用了一个quicksheet的插件，这个插件也有这个问题，我们解决方案是用离屏canvas解决的，我上面贴的那段代码也能解决这个问题，就是算文本的像素位置，然后截断
