### ISSUE TITLE
Get response json on add character in cell

### ISSUE THREAD

**Issue by Sonal1818** [myliang/x-spreadsheet#57]
Hi,
      I want updated json on add character in cell, currently i am getting only first character of cell in update json, For getting whole updated json i have to change or focus on another cell. So, It is possible to get updated json on change of any single character in cell.

Here i attach screen shot of tables with enter data "at" and in json only get single character "a" .

![cell](https://user-images.githubusercontent.com/47887852/53239429-0495eb00-36c2-11e9-93e4-a418ab988672.png)

Please help me to resolve this.

**Comment by myliang** [comment]
Once the input is complete, the data changes

**Comment by Sonal1818** [comment]
Hello Myliang,
         Thank you for reply.
         Once input is complete i have to click other cell then it consider data change. But i want without click any other cell, currently selected cell value should update in json.
          Please help me to achieve this.

**Comment by Sonal1818** [comment]
Hello Myliang,
                       I am waiting for your replay. Please help me to solve this.

**Comment by myliang** [comment]
![image](https://user-images.githubusercontent.com/718858/53735404-b5ba3380-3ec1-11e9-976c-dcf2fd391249.png)

**Comment by myliang** [comment]
fixed

**Comment by myliang** [comment]
> Hello Myliang,
> I am waiting for your replay. Please help me to solve this.

have fixied

**Comment by Sonal1818** [comment]
Hi Myliang,
           Thank you for update.
