### ISSUE TITLE
vue使用  x-spreadsheet

### ISSUE THREAD

**Issue by whatarey** [myliang/x-spreadsheet#586]

**Comment by whatarey** [comment]
帮作者回答一个问题

插件能够在 vue3使用，亲测
截图如下

![image](https://user-images.githubusercontent.com/35121432/160824545-b6d13081-d8b2-4713-b17a-064f63e44d86.png)

![image](https://user-images.githubusercontent.com/35121432/160824585-723679ae-da27-4b10-ba40-2fb68297c1e8.png)

遇到了几个问题
1
```
Error: Can't resolve 'less-loader'
```
参考issue
https://github.com/myliang/x-spreadsheet/issues/138


![6H%`1U0HZRJ85GQ(`}R6WND](https://user-images.githubusercontent.com/35121432/160824852-4a870730-4330-4432-afb6-d547bb57d969.jpg)

**Comment by whatarey** [comment]
ok

**Comment by 1Cr18Ni9** [comment]
对于 node12 和 vue2 的用户还需要安装less-loader, 用于加载内部的less样式。
兼容版本如下，亲测有效：
```shell
npm install less@3.0.4 less-loader@5.0.0 -D
```
