### ISSUE TITLE
可以把一些表单元素放进去吗？

### ISSUE THREAD

**Issue by yoyomule** [myliang/x-spreadsheet#59]
比如选择框，下拉框，图片上传框等？可以进行数据交互吗？

**Comment by wangzhedong** [comment]
我也有这个想法，自己fork一份自己改呗，代码还是很好读懂的

**Comment by yoyomule** [comment]
> 我也有这个想法，自己叉一份自己改呗，代码还是很好读懂的
没看到有文档。所以不太确定可以。但确实这样做很有用。

**Comment by wangzhedong** [comment]
我觉得应该是可以的，因为它的单元格的输入的时候其实就是个textarea标签

**Comment by myliang** [comment]
下拉框用处很多，上传图片感觉不是很常用

**Comment by myliang** [comment]
后面添加data validation时，会计入这样的功能

**Comment by yoyomule** [comment]
恩，主要是下拉框，选择框，日期选择组件等，或者留好位置和接口，这些组件由用户自己去引入，这样就可以匹配更多的组件。
![image](https://user-images.githubusercontent.com/10000818/53324359-8fbded80-391b-11e9-82d5-eb41eed47b5e.png)

**Comment by myliang** [comment]
@yoyomule @wangzhedong 在数据验证中已经支持了主要的表单功能： 日期，数字，下拉框等等.
现在可以在 https://myliang.github.io/x-spreadsheet/ 体验

**Comment by yoyomule** [comment]
谢谢，非常棒。另外希望后续可以考虑提供根据验证类型提供配套单元格样式，比如下拉框在单元格上能够看到下拉箭头，时间类型有选择器提示等等，目前单从样式上看不出验证类型。盼后面能提供的表单元素类型，如图片、单多选择框、是否等。再次感谢您的工作。
