### ISSUE TITLE
How to programmatically switch the sheet from code

### ISSUE THREAD

**Issue by ravinsharma7** [myliang/x-spreadsheet#601]
When the x-spreadsheet initialize it starts from the first sheet. I want to programmatically create another sheet and switch to it. What is the API I have to use to do this?

The readme is showing how configure, set data, etc only. No information on switching sheet from the code.

**Comment by hankaibo** [comment]
1. const s = new Spreadsheet("#x-spreadsheet-demo");
2. const item = s.bottomBar.items[x]; // x is index
3. s.bottomBar.clickSwap2(item);
