### ISSUE TITLE
I`m sorry, i mean when i set the freeze is 'C4', but the codes draw  from the third row and fourth col

### ISSUE THREAD

**Issue by 1369220324** [myliang/x-spreadsheet#62]
I`m sorry, i mean when i set the freeze is 'C4', but the codes draw  from the third row and fourth col
that hope draw from  the fourth row and third col

**Comment by 1369220324** [comment]
传入的参数是C4 应该是从C列4行开始固定的，但是代码却是在D列3行固定的

**Comment by myliang** [comment]
不包含当前单元格

**Comment by 1369220324** [comment]
参数的freeze的行和列反了，传入C10就会看的明显些了

**Comment by myliang** [comment]
已经修改了，只是Demo没更新，你在本地自己运行下就好了

**Comment by 1369220324** [comment]
change:
alphabet.js 文件的第38行，改为  return [parseInt(y, 10) - 1, indexAt(x)];
可以解决问题
