### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by luvsic3** [myliang/x-spreadsheet#620]
There are many pull request not reviewed and merged

**Comment by Kreijstal** [comment]
rip

**Comment by x68507** [comment]
Doesn't appear to be and the documentation is lacking so it's difficult to even perform basic customizations like changing column headers or modifying the context menu :(

**Comment by Kreijstal** [comment]
someone needs to fork it

**Comment by ayuechuan** [comment]
这个插件从整体上来看  更适合二次开发而非直接应用到项目中

**Comment by reviewher** [comment]
@x68507 the column labels ("A", "B", "C", ...) appear to be hardcoded https://github.com/myliang/x-spreadsheet/blob/master/src/component/table.js#L236
