### ISSUE TITLE
x-spreadsheet-editor的z-index太小，导致多次new Spreadsheet()之后编辑框会出现多个边框

### ISSUE THREAD

**Issue by zyplayer** [myliang/x-spreadsheet#637]
![image](https://user-images.githubusercontent.com/13164446/217011959-5f40c0e1-15cb-4cd1-955a-2d395192ebf7.png)

x-spreadsheet-editor的z-index太小，导致多次new Spreadsheet()之后编辑框会出现多个边框

解决：
1. 可以增加x-spreadsheet-editor的z-index，但不可能无限大吧，，
2. 每次new Spreadsheet()时，x-spreadsheet-selector 类上的z-index都是新的，重置它的z-index

不知道作者喜欢怎么做
我现在是覆盖了x-spreadsheet-editor的z-index为9999

**Comment by NameIsYearMonthDay** [comment]
试过把全局样式  *{ box-sizing:border-box } 去掉或者覆盖掉就不会出现两个边框了

**Comment by zyplayer** [comment]
是的，我这样处理了，忘了回复了~
好像是antdv组件库全局设置了 *{ box-sizing:border-box } 样式

**Comment by NameIsYearMonthDay** [comment]
这是自动回复：您好，我已收到您的邮件。
