### ISSUE TITLE
你好，我想请问下，如何才能吧您的插件功能集成到java的springboot项目里面去

### ISSUE THREAD

**Issue by giveahug** [myliang/x-spreadsheet#65]
您好，我是java后端开发，不太了解前端的语言体系，我看您的项目好像是nodejs之类的语言吗？当前我有个javaWeb项目是springboot的，我那个项目目前不是前后端分离，不知道如何才能把你这个插件功能集成进到我的项目里面，我项目的前端比较老还在用jsp，对怎么集成进jsp里面比较疑惑

**Comment by wangzhedong** [comment]
可以集成到jsp里面的，就跟引入jquery一样引入项目中，这个x-spreadsheet打完包之后会有一个打包编译后的文件的，你下载下来就可以了

**Comment by giveahug** [comment]
> 可以集成到jsp里面的，就跟引入jquery一样引入项目中，这个x-spreadsheet打完包之后会有一个打包编译后的文件的，你下载下来就可以了

你好，打包的过程可以讲的具体一点吗，目前没打过webpack的目录结构的包，打完包之后又是怎么引入项目呢

**Comment by myliang** [comment]
```html
<link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
<script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>

<script>
   x.spreadsheet('#xspreadsheet');
</script>
```

**Comment by myliang** [comment]
readme 有介绍

**Comment by giveahug** [comment]
> ```
> <link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
> <script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>
> 
> <script>
>    x.spreadsheet('#xspreadsheet');
> </script>
> ```

您好，我向您这样引入过，本地没有安装nodejs的情况下，运行项目查看功能的时候，谷歌浏览器F12的时候报js错误，直接这样引入还需要做其它什么装备工作吗

**Comment by giveahug** [comment]
您好，我看了您的readme，有这么一串代码，请问这串代码的作用是什么呢
`import Spreadsheet from "x-data-spreadsheet";
// If you need to override the default options, you can set the override
// const options = {};
// new Spreadsheet('#x-spreadsheet-demo', options);
new Spreadsheet("#x-spreadsheet-demo")
  .loadData({}) // load data
  .change(data => {
    // save data to db
  });
// default options
{
  showToolbar: true,
  showGrid: true,
  view: {
    height: () => document.documentElement.clientHeight,
    width: () => document.documentElement.clientWidth,
  },
  row: {
    len: 100,
    height: 25,
  },
  col: {
    len: 26,
    width: 100,
    indexWidth: 60,
    minWidth: 60,
  },
  style: {
    bgcolor: '#ffffff',
    align: 'left',
    valign: 'middle',
    textwrap: false,
    strike: false,
    underline: false,
    color: '#0a0a0a',
    font: {
      name: 'Helvetica',
      size: 10,
      bold: false,
      italic: false,
    },
  },
}`

**Comment by myliang** [comment]
> https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js

报什么错

**Comment by myliang** [comment]
> 您好，我看了您的readme，有这么一串代码，请问这串代码的作用是什么呢
> `import Spreadsheet from "x-data-spreadsheet"; // If you need to override the default options, you can set the override // const options = {}; // new Spreadsheet('#x-spreadsheet-demo', options); new Spreadsheet("#x-spreadsheet-demo") .loadData({}) // load data .change(data => { // save data to db }); // default options { showToolbar: true, showGrid: true, view: { height: () => document.documentElement.clientHeight, width: () => document.documentElement.clientWidth, }, row: { len: 100, height: 25, }, col: { len: 26, width: 100, indexWidth: 60, minWidth: 60, }, style: { bgcolor: '#ffffff', align: 'left', valign: 'middle', textwrap: false, strike: false, underline: false, color: '#0a0a0a', font: { name: 'Helvetica', size: 10, bold: false, italic: false, }, }, }`

这是npm方式开发用法

**Comment by giveahug** [comment]
> > https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js
> 
> 报什么错

您好，报的是图片上那个错误，我当前是在本地没部署nodejs情况下使用您的插件运行的项目报的错

index.js:21 Uncaught TypeError: Cannot read property 'appendChild' of null
 at new t (index.js:21)
    at Object.vi [as spreadsheet] (index.js:40)
    at to_addTableProject?mainCode=f716ba1b-2083-41ba-96cd-dd838dc91408:28

t | @ | index.js:21
-- | -- | --
  | vi | @ | index.js:40
  | (anonymous) | @ | to_addTableProject?m…6cd-dd838dc91408:28

以上是F12报错信息

**Comment by myliang** [comment]
对了，我这个项目不兼容ie浏览器

**Comment by giveahug** [comment]
> 对了，我这个项目不兼容ie浏览器

我用的是Google

**Comment by myliang** [comment]
> > 对了，我这个项目不兼容ie浏览器
> 
> 我用的是Google

我都试过了没有问题啊
```html
<!DOCTYPE html>
<html style="font-size:20px">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
</head>
<body>
  <div id="xspreadsheet"></div>
<script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>
<script>
   x.spreadsheet('#xspreadsheet');
</script>
</body>
</html>
```

**Comment by giveahug** [comment]
> > > 对了，我这个项目不兼容ie浏览器
> > 
> > 
> > 我用的是Google
> 
> 我都试过了没有问题啊
> 
> ```
> <!DOCTYPE html>
> <html style="font-size:20px">
> <head>
>   <meta charset="utf-8">
>   <link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
> </head>
> <body>
>   <div id="xspreadsheet"></div>
> <script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>
> <script>
>    x.spreadsheet('#xspreadsheet');
> </script>
> </body>
> </html>
> ```

不好意思是我界面切换错了~我试了下可以的~请问可以汉化吗

**Comment by myliang** [comment]
https://github.com/myliang/x-spreadsheet/wiki/Internationalization
参考这个
