### ISSUE TITLE
请问填写的数据信息怎么导出呢，还有就是支持单元格的合并吗

### ISSUE THREAD

**Issue by zhouhuan0910** [myliang/x-spreadsheet#66]

**Comment by myliang** [comment]
支持单元格合并，导出需要自己后台写代码

**Comment by zhouhuan0910** [comment]
> 支持单元格合并，导出需要自己后台写代码
单元格合并除了在代码里修改配置，可以通过页面操作来实现吗？还有就是单元格的边框颜色好像改配置中的styles.border也没什么效果

**Comment by zhouhuan0910** [comment]
> 支持单元格合并，导出需要自己后台写代码

单元格的边框颜色修改styles.border好像无效

**Comment by yanlingsishao** [comment]
@myliang 导出的后台容易写么，针对于excel的格式啥的

**Comment by myliang** [comment]
> @myliang 导出的后台容易写么，针对于excel的格式啥的

容易
