### ISSUE TITLE
输入参数freeze: 'E3',从C5开始画的，问题我给解决了，你看看呢

### ISSUE THREAD

**Issue by 1369220324** [myliang/x-spreadsheet#68]
change:
alphabet.js 文件的第38行，改为 return [parseInt(y, 10) - 1, indexAt(x)];
可以解决问题

**Comment by myliang** [comment]
这个问题早就解决了

**Comment by myliang** [comment]
> change:
> alphabet.js 文件的第38行，改为 return [parseInt(y, 10) - 1, indexAt(x)];
> 可以解决问题

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title><%= htmlWebpackPlugin.options.title %></title>
    
</head>
<body onload="load()">
  <div id="x-spreadsheet-demo"></div>
  <script>
    function load(){
      // x.spreadsheet.locale('zh-cn');
      x.spreadsheet('#x-spreadsheet-demo')
        .loadData({
          freeze: 'C3',
          styles: [
            {
              bgcolor: '#f4f5f8',
              textwrap: true,
              color: '#900b09',
              border: {
                top: ['thin', '#0366d6'],
                bottom: ['thin', '#0366d6'],
                right: ['thin', '#0366d6'],
                left: ['thin', '#0366d6'],
              },
            },
          ],
          merges: [
            'C3:D4',
          ],
          rows: {
            1: {
              cells: {
                0: { text: 'testingtesttestetst' },
                2: { text: 'testing' },
              },
            },
            2: {
              cells: {
                0: { text: 'render', style: 0 },
                1: { text: 'Hello' },
                2: { text: 'haha', merge: [1, 1] },
              }
            },
            8: {
              cells: {
                8: { text: 'border test', style: 0 },
              }
            }
          },
        }).change((cdata) => console.log(cdata));
    }
  </script>
</body>
</html>

```
![image](https://user-images.githubusercontent.com/718858/54424253-72778480-474d-11e9-92aa-06f1b38da7ab.png)

**Comment by 1369220324** [comment]
.loadData({
          freeze: 'E3',
          styles: [
            {
              bgcolor: '#f4f5f8',
              textwrap: true,
              color: '#900b09',
              border: {
                top: ['thin', '#0366d6'],
                bottom: ['thin', '#0366d6'],
                right: ['thin', '#0366d6'],
                left: ['thin', '#0366d6'],
              },
            },
          ],
          merges: [
            'C3:D4',
          ],
          rows: {
            1: {
              cells: {
                0: { text: 'testingtesttestetst' },
                2: { text: 'testing' },
              },
            },
            2: {
              cells: {
                0: { text: 'render', style: 0 },
                1: { text: 'Hello' },
                2: { text: 'haha', merge: [1, 1] },
              }
            },
            8: {
              cells: {
                8: { text: 'border test', style: 0 },
              }
            }
          },
        }).change((cdata) => console.log(cdata));
