### ISSUE TITLE
您好，想问下表格上的数据怎样传到后台

### ISSUE THREAD

**Issue by giveahug** [myliang/x-spreadsheet#71]
您好，我看到您这个excel表格是用canvas标签画的，我有个疑惑，为什么我F12看控制台，发现好多table标签，但是没有一个table标签里面存储我写的数据，并且我Ctrl+F搜索我填的数据，发现在控制台里面找不到，不知道您是把数据存在哪？请问我要怎样把excel上面的数据全部提交到后台去呢

**Comment by myliang** [comment]
> 您好，我看到您这个excel表格是用canvas标签画的，我有个疑惑，为什么我F12看控制台，发现好多table标签，但是没有一个table标签里面存储我写的数据，并且我Ctrl+F搜索我填的数据，发现在控制台里面找不到，不知道您是把数据存在哪？请问我要怎样把excel上面的数据全部提交到后台去呢

```javascript
import Spreadsheet from "x-data-spreadsheet";
// If you need to override the default options, you can set the override
// const options = {};
// new Spreadsheet('#x-spreadsheet-demo', options);
new Spreadsheet("#x-spreadsheet-demo")
  .loadData({}) // load data 
  .change(data => {
    // save data to db
  });
```

change 这个方法的参数就是要保存到后台的数据
loadData 加载数据库的数据（即change的值）
getData 方法得到内存中的数据

**Comment by giveahug** [comment]
> > 您好，我看到您这个excel表格是用canvas标签画的，我有个疑惑，为什么我F12看控制台，发现好多table标签，但是没有一个table标签里面存储我写的数据，并且我Ctrl+F搜索我填的数据，发现在控制台里面找不到，不知道您是把数据存在哪？请问我要怎样把excel上面的数据全部提交到后台去呢
> 
> ```js
> import Spreadsheet from "x-data-spreadsheet";
> // If you need to override the default options, you can set the override
> // const options = {};
> // new Spreadsheet('#x-spreadsheet-demo', options);
> new Spreadsheet("#x-spreadsheet-demo")
>   .loadData({}) // load data 
>   .change(data => {
>     // save data to db
>   });
> ```
> 
> change 这个方法的参数就是要保存到后台的数据
> loadData 加载数据库的数据（即change的值）
> getData 方法得到内存中的数据

您好，这段代码一般放在什么位置呢，因为我看到import字样，之前在前端没见过这样import的方式

**Comment by myliang** [comment]
> > > 您好，我看到您这个excel表格是用canvas标签画的，我有个疑惑，为什么我F12看控制台，发现好多table标签，但是没有一个table标签里面存储我写的数据，并且我Ctrl+F搜索我填的数据，发现在控制台里面找不到，不知道您是把数据存在哪？请问我要怎样把excel上面的数据全部提交到后台去呢
> > 
> > 
> > ```js
> > import Spreadsheet from "x-data-spreadsheet";
> > // If you need to override the default options, you can set the override
> > // const options = {};
> > // new Spreadsheet('#x-spreadsheet-demo', options);
> > new Spreadsheet("#x-spreadsheet-demo")
> >   .loadData({}) // load data 
> >   .change(data => {
> >     // save data to db
> >   });
> > ```
> > 
> > 
> > change 这个方法的参数就是要保存到后台的数据
> > loadData 加载数据库的数据（即change的值）
> > getData 方法得到内存中的数据
> 
> 您好，这段代码一般放在什么位置呢，因为我看到import字样，之前在前端没见过这样import的方式

<link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.7/dist/xspreadsheet.css">
<script src="https://unpkg.com/x-data-spreadsheet@1.0.7/dist/xspreadsheet.js"></script>

<script>
   x.spreadsheet('#xspreadsheet')
  .loadData({}) // load data 
    .change(data => {
      // save data to db
    });
</script>

**Comment by giveahug** [comment]
> > > > 您好，我看到您这个excel表格是用canvas标签画的，我有个疑惑，为什么我F12看控制台，发现好多table标签，但是没有一个table标签里面存储我写的数据，并且我Ctrl+F搜索我填的数据，发现在控制台里面找不到，不知道您是把数据存在哪？请问我要怎样把excel上面的数据全部提交到后台去呢
> > > 
> > > 
> > > ```js
> > > import Spreadsheet from "x-data-spreadsheet";
> > > // If you need to override the default options, you can set the override
> > > // const options = {};
> > > // new Spreadsheet('#x-spreadsheet-demo', options);
> > > new Spreadsheet("#x-spreadsheet-demo")
> > >   .loadData({}) // load data 
> > >   .change(data => {
> > >     // save data to db
> > >   });
> > > ```
> > > 
> > > 
> > > change 这个方法的参数就是要保存到后台的数据
> > > loadData 加载数据库的数据（即change的值）
> > > getData 方法得到内存中的数据
> > 
> > 
> > 您好，这段代码一般放在什么位置呢，因为我看到import字样，之前在前端没见过这样import的方式
> 
> ```
> <link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
> <script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>
> 
> <script>
>    x.spreadsheet('#xspreadsheet')
>     .loadData({}) // load data 
>     .change(data => {
>       // save data to db
>     });
> </script>
> ```

你好，请问这段代码import Spreadsheet from "x-data-spreadsheet";
怎么导入jsp里面，我的项目没有前后端分离

**Comment by myliang** [comment]
直接如下使用就行了，不需要其他的代码
```html
<link rel="stylesheet" href="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.css">
<script src="https://unpkg.com/x-data-spreadsheet@1.0.9/dist/xspreadsheet.js"></script>

<script>
   x.spreadsheet('#xspreadsheet')
    .loadData({}) // load data 
    .change(data => {
      // save data to db
    });
</script>
```

**Comment by giveahug** [comment]
> ```
> <script>
>    x.spreadsheet('#xspreadsheet')
>     .loadData({}) // load data 
>     .change(data => {
>       // save data to db
>     });
> </script>
> ```
可以啦，谢谢。不过我还有一个问题，就是通过函数=SUM(A1:D4)计算出来的值我通过输出change里面的data--》console.log(data)--》找不到通过sum函数计算出来的的值，请问这个值存在哪个地方

**Comment by giveahug** [comment]
![image](https://user-images.githubusercontent.com/34709078/54580320-86b7cc00-4a42-11e9-967b-b7c5bf724da5.png)
发现了个问题，输入SUM函数时渲染会出现问题

**Comment by giveahug** [comment]
> >     .change(data => {
> >       // save data to db
> >     });
> > </script>
> > ```
> 
> 可以啦，谢谢。不过我还有一个问题，就是通过函数=SUM(A1:D4)计算出来的值我通过输出change里面的data--》console.log(data)--》找不到通过sum函数计算出来的的值，请问这个值存在哪个地方

**Comment by myliang** [comment]
> > ```
> > <script>
> >    x.spreadsheet('#xspreadsheet')
> >     .loadData({}) // load data 
> >     .change(data => {
> >       // save data to db
> >     });
> > </script>
> > ```
> 
> 可以啦，谢谢。不过我还有一个问题，就是通过函数=SUM(A1:B1)计算出来的值我通过输出change里面的data--》console.log(data)--》找不到通过sum函数计算出来的的值，请问这个值存在哪个地方
> ![image](https://user-images.githubusercontent.com/34709078/54580435-047bd780-4a43-11e9-8b3c-51478936483e.png)
> 想知道这个3的值存在哪
> ![image](https://user-images.githubusercontent.com/34709078/54580531-794f1180-4a43-11e9-943c-41f0c15f2082.png)

表达式是动态计算的（暂时不存储值）

**Comment by myliang** [comment]
> ![image](https://user-images.githubusercontent.com/34709078/54580320-86b7cc00-4a42-11e9-967b-b7c5bf724da5.png)
> ![image](https://user-images.githubusercontent.com/34709078/54580379-cbdbfe00-4a42-11e9-8790-8938b00e65c1.png)
> ![image](https://user-images.githubusercontent.com/34709078/54580394-db5b4700-4a42-11e9-8133-484480d6750f.png)
> 
> 发现了个问题，输入SUM函数时渲染会出现问题

表达式写法错误，不知A1:这种表达式

**Comment by giveahug** [comment]
> > > ```
> > > <script>
> > >    x.spreadsheet('#xspreadsheet')
> > >     .loadData({}) // load data 
> > >     .change(data => {
> > >       // save data to db
> > >     });
> > > </script>
> > > ```
> > 
> > 
> > 可以啦，谢谢。不过我还有一个问题，就是通过函数=SUM(A1:B1)计算出来的值我通过输出change里面的data--》console.log(data)--》找不到通过sum函数计算出来的的值，请问这个值存在哪个地方
> > ![image](https://user-images.githubusercontent.com/34709078/54580435-047bd780-4a43-11e9-8b3c-51478936483e.png)
> > 想知道这个3的值存在哪
> > ![image](https://user-images.githubusercontent.com/34709078/54580531-794f1180-4a43-11e9-943c-41f0c15f2082.png)
> 
> 表达式是动态计算的（暂时不存储值）

那就是表达式的值要在后台计算吗

**Comment by giveahug** [comment]
> > > > ```
> > > > <script>
> > > >    x.spreadsheet('#xspreadsheet')
> > > >     .loadData({}) // load data 
> > > >     .change(data => {
> > > >       // save data to db
> > > >     });
> > > > </script>
> > > > ```
> > > 
> > > 
> > > 可以啦，谢谢。不过我还有一个问题，就是通过函数=SUM(A1:B1)计算出来的值我通过输出change里面的data--》console.log(data)--》找不到通过sum函数计算出来的的值，请问这个值存在哪个地方
> > > ![image](https://user-images.githubusercontent.com/34709078/54580435-047bd780-4a43-11e9-8b3c-51478936483e.png)
> > > 想知道这个3的值存在哪
> > > ![image](https://user-images.githubusercontent.com/34709078/54580531-794f1180-4a43-11e9-943c-41f0c15f2082.png)
> > 
> > 
> > 表达式是动态计算的（暂时不存储值）
> 
> 那就是表达式的值要在后台计算吗

那计算A1和B1的和，的表达式需要怎么写

> > ![image](https://user-images.githubusercontent.com/34709078/54580320-86b7cc00-4a42-11e9-967b-b7c5bf724da5.png)
> > ![image](https://user-images.githubusercontent.com/34709078/54580379-cbdbfe00-4a42-11e9-8790-8938b00e65c1.png)
> > ![image](https://user-images.githubusercontent.com/34709078/54580394-db5b4700-4a42-11e9-8133-484480d6750f.png)
> > 发现了个问题，输入SUM函数时渲染会出现问题
> 
> 表达式写法错误，不知A1:这种表达式


那计算A1和B1的和，的表达式需要怎么写

**Comment by myliang** [comment]
不明白你干什么，只要计算结果，还是什么，程序暂时没有存储计算结果

**Comment by giveahug** [comment]
> 不明白你干什么，只要计算结果，还是什么，程序暂时没有存储计算结果

因为我想把您的这个excel做成表单提交的形式，有新建和查看两种状态，意思说计算表达式（用于编辑的时候显示）和表达式的结果值（用于查看的时候显示）俩个都需要，如果有结果值直接传到后台就比较方便，没有的话传到后台还需要计算一遍编辑麻烦~~所以就问您能不能通过js代码把结果值一起传到后台去~~

**Comment by myliang** [comment]
> > 不明白你干什么，只要计算结果，还是什么，程序暂时没有存储计算结果
> 
> 因为我想把您的这个excel做成表单提交的形式，有新建和查看两种状态，意思说计算表达式（用于编辑的时候显示）和表达式的结果值（用于查看的时候显示）俩个都需要，如果有结果值直接传到后台就比较方便，没有的话传到后台还需要计算一遍比较麻烦所以就问您能不能通过js代码把结果值一起传到后台去

你这个需求，后面会考虑添加的

**Comment by giveahug** [comment]
> > > 不明白你干什么，只要计算结果，还是什么，程序暂时没有存储计算结果
> > 
> > 
> > 因为我想把您的这个excel做成表单提交的形式，有新建和查看两种状态，意思说计算表达式（用于编辑的时候显示）和表达式的结果值（用于查看的时候显示）俩个都需要，如果有结果值直接传到后台就比较方便，没有的话传到后台还需要计算一遍比较麻烦所以就问您能不能通过js代码把结果值一起传到后台去
> 
> 你这个需求，后面会考虑添加的

好的哈~~

**Comment by giveahug** [comment]
你好，还在嘛~
我还有个需求，就是我有个查看表单，点击弹出这个excel表格，然后需要隐藏工具栏和禁止编辑表格内容，这俩个需求，请问有实现方法吗~

**Comment by myliang** [comment]
后面会考虑

**Comment by giveahug** [comment]
同一个页面可以有两个这个吗：
x.spreadsheet('#xspreadsheet')
	.loadData(
			alert(222)
			)
	.change(data => {
		console.log(data);
	});
我使用第二次这个的时候再change函数里面报错了：
![image](https://user-images.githubusercontent.com/34709078/54594956-ac59cb00-4a6c-11e9-9198-4bb190500e43.png)

![Uploading image.png…]()
