### ISSUE TITLE
单元格合并后，合并的单元格的bottom-border不见了

### ISSUE THREAD

**Issue by 1369220324** [myliang/x-spreadsheet#72]

**Comment by 1369220324** [comment]
底部的线和右边的线都不见了

**Comment by 1369220324** [comment]
draw.js的336行，换成
ctx.rect(npx(x) - 0.5, npx(y) - 0.5, npx(width - 0.5), npx(height - 0.5));
解决问题

**Comment by 1369220324** [comment]
暂时解决，不过还是影响别的，还没看懂作者的思路

**Comment by 1369220324** [comment]
ctx.rect(npx(x) - 0.1, npx(y) - 0.1, npx(width - 0.1), npx(height - 0.1));

**Comment by myliang** [comment]
暂时建议先合并单元格，最后设置边框

**Comment by 1369220324** [comment]
好的
