### ISSUE TITLE
index.html中引入zh-cn报错

### ISSUE THREAD

**Issue by liucien** [myliang/x-spreadsheet#76]
直接将项目clone下来后取消index.html中第13行的注释报错，请问一下是我改的方式不对么
![image](https://user-images.githubusercontent.com/32785166/54729228-42047000-4bbd-11e9-893d-9bd6a9fd7d0d.png)
![image](https://user-images.githubusercontent.com/32785166/54729237-50528c00-4bbd-11e9-8d26-e4f1ceddd389.png)

**Comment by myliang** [comment]
https://github.com/myliang/x-spreadsheet/wiki/Internationalization

**Comment by liucien** [comment]
使用import引入后中文可以出来了，但是数据导入仍旧报错了，我这里第三方框架用的vue
![image](https://user-images.githubusercontent.com/32785166/54732507-1c806200-4bcf-11e9-9791-28436a601762.png)
![image](https://user-images.githubusercontent.com/32785166/54732521-2dc96e80-4bcf-11e9-99dd-cd44c9b8ecee.png)

**Comment by myliang** [comment]
用1.0.9版本

**Comment by liucien** [comment]
好了，谢谢

**Comment by iTaster** [comment]
== 劳烦更新时在主页 README 说明一下

>  import  'x-data-spreadsheet/dist/locale/zh-cn';
> 改为：
> import zhCN from 'x-data-spreadsheet/dist/locale/zh-cn';
> 
> Spreadsheet.locale('zh-cn')
> 改为
> Spreadsheet.locale('zh-cn', zhCN)
