### ISSUE TITLE
高度怎么设置不是窗口高度

### ISSUE THREAD

**Issue by zhouhuan0910** [myliang/x-spreadsheet#77]
![image](https://user-images.githubusercontent.com/22877154/54806211-4e1f2900-4cb4-11e9-9135-ca633d5bc1ab.png)
你好，我按照文档说明，想覆盖默认的高度，但是并不生效，请问是这样修改吗

**Comment by myliang** [comment]
返回number类型

**Comment by zhouhuan0910** [comment]
你好，按照返回Number类型好像也并不能生效。我可以尝试修改css可以设置尺寸。


现在使用时候，滚动条已经滑到最右侧，但是有一部分内容缺失了，如图，其实数据还有 “第十一天”这些，请问这是什么原因呢

**Comment by zhouhuan0910** [comment]
![image](https://user-images.githubusercontent.com/22877154/54890686-66c25580-4ee5-11e9-9bcc-0e87a694b643.png)

**Comment by myliang** [comment]
这个修改还没发布版本，等几天后版本更新
