### ISSUE TITLE
编辑的时候显示框问题

### ISSUE THREAD

**Issue by zhouhuan0910** [myliang/x-spreadsheet#79]
![image](https://user-images.githubusercontent.com/22877154/54969287-86767e00-4fb8-11e9-9e81-5b30f3f53c4f.png)
你好，引入之后，点击编辑的时候，出现了两个内容，想知道这个是什么原因导致的呢？会跟版本有关系吗？

**Comment by myliang** [comment]
先用1.0.9版本

**Comment by zhouhuan0910** [comment]
好像其他版本也有这个问题哦，试了1.0.9和1.0.7，
最近在看一下这个插件的是否满足我的需求，前几天还没有这个问题，今天才出现的

**Comment by myliang** [comment]
> 好像其他版本也有这个问题哦，试了1.0.9和1.0.7，
> 最近在看一下这个插件的是否满足我的需求，前几天还没有这个问题，今天才出现的

我这没有出现这个问题，你是什么浏览器

**Comment by zhouhuan0910** [comment]
> > 好像其他版本也有这个问题哦，试了1.0.9和1.0.7，
> > 最近在看一下这个插件的是否满足我的需求，前几天还没有这个问题，今天才出现的
> 
> 我这没有出现这个问题，你是什么浏览器

chrome 73.0.3683.75

**Comment by myliang** [comment]
![image](https://user-images.githubusercontent.com/718858/54980306-59d65c80-4fe0-11e9-96ac-41cc84747cac.png)
是不是和你自己的样式冲突了

**Comment by zhouhuan0910** [comment]
> ![image](https://user-images.githubusercontent.com/718858/54980306-59d65c80-4fe0-11e9-96ac-41cc84747cac.png)
> 是不是和你自己的样式冲突了

我也没有改过默认的样式，只是设置了一个宽度，而且开始的时候是好的，今天用的时候发现了这个问题，什么情况下会改变这个样式呢？
