### ISSUE TITLE
这个应该是对开源组件的封装 或者改了源码吧 ？

### ISSUE THREAD

**Issue by uk0** [myliang/x-spreadsheet#86]
https://github.com/handsontable/handsontable

**Comment by myliang** [comment]
不是对开源的组件handsontable的封装，我是模仿的google sheet
handsontable是table渲染模式，我的是canvas渲染

**Comment by myliang** [comment]
> https://github.com/handsontable/handsontable

不依赖任何开源组件

**Comment by myliang** [comment]
@uk0

**Comment by lemonc747** [comment]
@myliang 请教大佬，canvas渲染是出于什么考虑呢，性能吗？
