### ISSUE TITLE
合并表格后复制结果错误

### ISSUE THREAD

**Issue by zhylmzr** [myliang/x-spreadsheet#88]
环境: macOS 10.14, Chrome 73

1. 复制 `haha` 表格到 `Hello` 表格后原单元格不应该还是合并状态, 参考 google sheet.
![Snipaste_2019-04-02_14-05-44](https://user-images.githubusercontent.com/15730824/55379761-a1189c00-5550-11e9-8bb2-2dd47c24a2f0.png)
![Snipaste_2019-04-02_14-07-06](https://user-images.githubusercontent.com/15730824/55379764-a4138c80-5550-11e9-8aed-d56744b40a2e.png)

2. 在右边单元格的左侧小范围内多次点击可导致选中B~D三列
![3](https://user-images.githubusercontent.com/15730824/55379902-15533f80-5551-11e9-89bb-0d84a3a6d406.png)

**Comment by myliang** [comment]
@zhylmzr 已做判断处理
