### ISSUE TITLE
怎么清除画布？

### ISSUE THREAD

**Issue by WayneVN** [myliang/x-spreadsheet#94]
new出画布之后，我数据发生变化了，需要重绘，但是这时候相当于重新new了；
但是我需要吧之前老的给清除了；
能给提供个clear之类的方法不？
在线急等~

**Comment by myliang** [comment]
loadData方法就可以

**Comment by WayneVN** [comment]
跪谢~

**Comment by yansenlei** [comment]
@myliang 
怎么清空？editor. loadData({}) 不能清空
