### ISSUE TITLE
你好，能不能加个保存和关闭功能呢

### ISSUE THREAD

**Issue by echosunshine** [myliang/x-spreadsheet#97]
保存：点击保存之后，将修过后的数据一次性提交给后台，或者是让程序知道这是最后一次修改，将数据提交，而不是每次修改一个单元格提交一次，减少提交次数啊
关闭：不需要使用表格时，可以及时关闭，需要的时候再打开就可以

**Comment by myliang** [comment]
getData()

**Comment by danzi2017** [comment]
getData()放在哪里？怎么写？好像一进入页面酒自动加载这个方法了。
