### ISSUE TITLE
请问new 出来的示例有办法销毁吗？

### ISSUE THREAD

**Issue by zhouhuan0910** [myliang/x-spreadsheet#98]
现在我是有这样一个操作，有一个tab切换功能，然后是电子表格，切换不同的tab，表格加载不同的option。如果我每次切换的时候都去new一下这个实例，会生成一个新的表格显示。
所以，想请问一下，有没有办法销毁，或者有没有办法在使用某个表格实例的过程中重新setOptions

**Comment by myliang** [comment]
loadData方法
